app = "router-security-dashboard"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048

[env]
  PORT = "3000"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/public/"